# Generated by Django 3.1.1 on 2020-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flawedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
